// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in * Menu Settings → Navigation*
 */
export interface MenuSettingsDocumentDataNavigationItem {
  /**
   * Label field in * Menu Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in * Menu Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * CTA button field in * Menu Settings → Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: menu_settings.navigation[].cta_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta_button: prismic.BooleanField;
}

/**
 * Content for  Menu Settings documents
 */
interface MenuSettingsDocumentData {
  /**
   * Site Name field in * Menu Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Alejandra Leyva
   * - **API ID Path**: menu_settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_name: prismic.KeyTextField;

  /**
   * subslogan field in * Menu Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Fotógrafa
   * - **API ID Path**: menu_settings.subslogan
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subslogan: prismic.KeyTextField;

  /**
   * Meta Description field in * Menu Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * General Image field in * Menu Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_settings.general_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  general_image: prismic.ImageField<never>;

  /**
   * Navigation field in * Menu Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<
    Simplify<MenuSettingsDocumentDataNavigationItem>
  >;
}

/**
 *  Menu Settings document from Prismic
 *
 * - **API ID**: `menu_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MenuSettingsDocumentData>,
    "menu_settings",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ProjectCardsSlice
  | PhotoGridSlice
  | HeroGridSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = MenuSettingsDocument | PageDocument;

/**
 * Item in *HeroGrid → Default → Primary → Hero Image*
 */
export interface HeroGridSliceDefaultPrimaryHeroImageItem {
  /**
   * Carusel Image field in *HeroGrid → Default → Primary → Hero Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_grid.default.primary.hero_image[].carusel_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carusel_image: prismic.ImageField<never>;

  /**
   * Image Description field in *HeroGrid → Default → Primary → Hero Image*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_grid.default.primary.hero_image[].image_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_description: prismic.KeyTextField;
}

/**
 * Primary content in *HeroGrid → Default → Primary*
 */
export interface HeroGridSliceDefaultPrimary {
  /**
   * Hero Image field in *HeroGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_grid.default.primary.hero_image[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero_image: prismic.GroupField<
    Simplify<HeroGridSliceDefaultPrimaryHeroImageItem>
  >;
}

/**
 * Default variation for HeroGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroGrid*
 */
type HeroGridSliceVariation = HeroGridSliceDefault;

/**
 * HeroGrid Shared Slice
 *
 * - **API ID**: `hero_grid`
 * - **Description**: HeroGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroGridSlice = prismic.SharedSlice<
  "hero_grid",
  HeroGridSliceVariation
>;

/**
 * Item in *PhotoGrid → Default → Primary → Grid of Images*
 */
export interface PhotoGridSliceDefaultPrimaryGridOfImagesItem {
  /**
   * Image field in *PhotoGrid → Default → Primary → Grid of Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_grid.default.primary.grid_of_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Description field in *PhotoGrid → Default → Primary → Grid of Images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_grid.default.primary.grid_of_images[].image_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  image_description: prismic.RichTextField;
}

/**
 * Primary content in *PhotoGrid → Default → Primary*
 */
export interface PhotoGridSliceDefaultPrimary {
  /**
   * Grid of Images field in *PhotoGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_grid.default.primary.grid_of_images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grid_of_images: prismic.GroupField<
    Simplify<PhotoGridSliceDefaultPrimaryGridOfImagesItem>
  >;
}

/**
 * Default variation for PhotoGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhotoGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PhotoGrid*
 */
type PhotoGridSliceVariation = PhotoGridSliceDefault;

/**
 * PhotoGrid Shared Slice
 *
 * - **API ID**: `photo_grid`
 * - **Description**: PhotoGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoGridSlice = prismic.SharedSlice<
  "photo_grid",
  PhotoGridSliceVariation
>;

/**
 * Item in *ProjectCards → Default → Primary → Card Group*
 */
export interface ProjectCardsSliceDefaultPrimaryCardGroupItem {
  /**
   * Card Title field in *ProjectCards → Default → Primary → Card Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cards.default.primary.card_group[].card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_title: prismic.KeyTextField;

  /**
   * Gallery Image field in *ProjectCards → Default → Primary → Card Group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cards.default.primary.card_group[].gallery_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gallery_image: prismic.ImageField<never>;

  /**
   * Button View field in *ProjectCards → Default → Primary → Card Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ver Galería
   * - **API ID Path**: project_cards.default.primary.card_group[].button_view
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_view: prismic.KeyTextField;

  /**
   * Page Link field in *ProjectCards → Default → Primary → Card Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cards.default.primary.card_group[].page_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_link: prismic.LinkField;
}

/**
 * Primary content in *ProjectCards → Default → Primary*
 */
export interface ProjectCardsSliceDefaultPrimary {
  /**
   * Section Title field in *ProjectCards → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Nombre de Section
   * - **API ID Path**: project_cards.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;

  /**
   * Card Group field in *ProjectCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_cards.default.primary.card_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card_group: prismic.GroupField<
    Simplify<ProjectCardsSliceDefaultPrimaryCardGroupItem>
  >;
}

/**
 * Default variation for ProjectCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectCards*
 */
type ProjectCardsSliceVariation = ProjectCardsSliceDefault;

/**
 * ProjectCards Shared Slice
 *
 * - **API ID**: `project_cards`
 * - **Description**: ProjectCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectCardsSlice = prismic.SharedSlice<
  "project_cards",
  ProjectCardsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MenuSettingsDocument,
      MenuSettingsDocumentData,
      MenuSettingsDocumentDataNavigationItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroGridSlice,
      HeroGridSliceDefaultPrimaryHeroImageItem,
      HeroGridSliceDefaultPrimary,
      HeroGridSliceVariation,
      HeroGridSliceDefault,
      PhotoGridSlice,
      PhotoGridSliceDefaultPrimaryGridOfImagesItem,
      PhotoGridSliceDefaultPrimary,
      PhotoGridSliceVariation,
      PhotoGridSliceDefault,
      ProjectCardsSlice,
      ProjectCardsSliceDefaultPrimaryCardGroupItem,
      ProjectCardsSliceDefaultPrimary,
      ProjectCardsSliceVariation,
      ProjectCardsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
