// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  hero_grid: dynamic(() => import("./HeroGrid")),
  media_grid: dynamic(() => import("./MediaGrid")),
  photo_grid: dynamic(() => import("./PhotoGrid")),
  project_cards: dynamic(() => import("./ProjectCards")),
  rich_text: dynamic(() => import("./RichText")),
  two_col_content: dynamic(() => import("./TwoColContent")),
};
